/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistant;


import Business.EcoSystem;
import Business.Organization.LabOrganization;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.RecyclableWaste;
import Business.WorkQueue.SegregationTestWorkResult;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author poojitha
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    EcoSystem business;
    private LabOrganization labOrganization;
    ArrayList<WorkRequest> result =new ArrayList<WorkRequest>();
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business,LabTestWorkRequest request,LabOrganization labOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business = business;
        this.labOrganization = labOrganization;
        result = labOrganization.getWorkQueue().getWorkRequestList();
        populateDetails();
    }
    
    public void populateDetails(){
     
      for (int i=0; i<result.size();i++) {
        LabTestWorkRequest labTestWorkRequest = (LabTestWorkRequest) result.get(i);
        RecyclableWaste recyclableWaste =  labTestWorkRequest.getRecyclableWaste();
        if(recyclableWaste.getStatus()=="Pending"){
        syringesTotalJText.setText(String.valueOf(recyclableWaste.getNumberOfSyringes()));
        plasticDisposablesTotalJText.setText(String.valueOf(recyclableWaste.getNumberOfPlasticDisposables()));
        xRayFilmsTotalJText.setText(String.valueOf(recyclableWaste.getNumberOfXRayFilms()));
        bpCuffsTotalJText.setText(String.valueOf(recyclableWaste.getNumberOfBPCuffAndBulbs()));
        break;
        }
      }
    }
static boolean isNumberValid(String number)
    {
        String regex = "[\\\\s]*[0-9]*[0-9]+";
        return number.matches(regex);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bpCuffsRecyclableJText = new javax.swing.JTextField();
        bpCuffsTotalJText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        plasticDisposablesTotalJText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        xRayFilmsTotalJText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        syringesTotalJText = new javax.swing.JTextField();
        syringesRecyclableJText = new javax.swing.JTextField();
        plasticDisposableRecyclableJText = new javax.swing.JTextField();
        xRayFilmsRecyclableJText = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lab Assistant Work Area - Test Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 50));
        add(bpCuffsRecyclableJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 50, -1));

        bpCuffsTotalJText.setEnabled(false);
        add(bpCuffsTotalJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 50, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Of Syringes :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("No. Of Plastic Disposables : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("No. Of X-Ray Films : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, -1));

        plasticDisposablesTotalJText.setEnabled(false);
        add(plasticDisposablesTotalJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 50, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("No. Of BP Cuff and Flouroscent Bulbs :  ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, -1));

        xRayFilmsTotalJText.setEnabled(false);
        add(xRayFilmsTotalJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 50, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Total Quantity");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Recyclable Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        syringesTotalJText.setEnabled(false);
        add(syringesTotalJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 50, -1));
        add(syringesRecyclableJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 50, -1));
        add(plasticDisposableRecyclableJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 50, -1));
        add(xRayFilmsRecyclableJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 50, -1));

        submitJButton.setBackground(new java.awt.Color(0, 153, 153));
        submitJButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        backJButton.setBackground(new java.awt.Color(0, 153, 153));
        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        syringesRecyclableJText.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel2.setForeground(Color.BLACK);
        
        plasticDisposableRecyclableJText.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel3.setForeground(Color.BLACK);
        
        xRayFilmsRecyclableJText.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel4.setForeground(Color.BLACK);
        
        bpCuffsRecyclableJText.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel5.setForeground(Color.BLACK);
        
        
        if(isNumberValid(syringesRecyclableJText.getText()) == false || syringesRecyclableJText.getText() == null || syringesRecyclableJText.getText().equals(""))
        {
            syringesRecyclableJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel2.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter a valid number for No. of Syringes");
        }
        else if(isNumberValid(plasticDisposableRecyclableJText.getText()) == false || plasticDisposableRecyclableJText.getText() == null || plasticDisposableRecyclableJText.getText().equals(""))
        {
            plasticDisposableRecyclableJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel3.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter a valid number for No. Of Plastic Disposables");
        }
        else if(isNumberValid(xRayFilmsRecyclableJText.getText()) == false || xRayFilmsRecyclableJText.getText() == null || xRayFilmsRecyclableJText.getText().equals(""))
        {
            xRayFilmsRecyclableJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel4.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter a valid number for No. Of X-Ray Films");
        }
        else if(isNumberValid(bpCuffsRecyclableJText.getText()) == false || bpCuffsRecyclableJText.getText() == null || bpCuffsRecyclableJText.getText().equals(""))
        {
            bpCuffsRecyclableJText.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel5.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please enter a valid number for No. Of BP Cuff and Flouroscent Bulbs");
        }
        else
        {
        ArrayList<WorkRequest> result = business.getWorkQueue().getWorkRequestList();    
         for (int i=0; i<result.size();i++) {
            SegregationTestWorkResult segregationResult = (SegregationTestWorkResult) result.get(i);
       
            int numberOfSyringes = Integer.parseInt(syringesRecyclableJText.getText());
            int numberOfPlasticDisposables = Integer.parseInt(plasticDisposableRecyclableJText.getText());
            int numberOfXRayFilms = Integer.parseInt(xRayFilmsRecyclableJText.getText());
            int numberOfBPCuffsAndBulbs = Integer.parseInt(bpCuffsRecyclableJText.getText());
            
            int totalNumberOfSyringes = Integer.parseInt(syringesTotalJText.getText());
            int totalNumberOfPlasticDisposables = Integer.parseInt(plasticDisposablesTotalJText.getText());
            int totalNumberOfXRayFilms = Integer.parseInt(xRayFilmsTotalJText.getText());
            int totalNumberOfBPCuffsAndBulbs = Integer.parseInt(bpCuffsTotalJText.getText());
            
            if(totalNumberOfSyringes<numberOfSyringes){
                JOptionPane.showMessageDialog(null, "Please enter quantity less than Total Quantity");
                return;
            }
            if(totalNumberOfPlasticDisposables<numberOfPlasticDisposables){
                JOptionPane.showMessageDialog(null, "Please enter quantity less than Total Quantity");
                return;
            }
            if(totalNumberOfXRayFilms<numberOfXRayFilms){
                JOptionPane.showMessageDialog(null, "Please enter quantity less than Total Quantity");
                return;
            }
            if(totalNumberOfBPCuffsAndBulbs<numberOfBPCuffsAndBulbs){
                JOptionPane.showMessageDialog(null, "Please enter quantity less than Total Quantity");
                return;
            }
            double decomposingQuantity =  ((totalNumberOfSyringes-numberOfSyringes)*(0.03))+((totalNumberOfPlasticDisposables-numberOfPlasticDisposables)*(2))+((totalNumberOfXRayFilms-numberOfXRayFilms)*(280))+((totalNumberOfBPCuffsAndBulbs-numberOfBPCuffsAndBulbs)*(3));
            RecyclableWaste recyclableWaste = segregationResult.getRecyclableWaste();
            if(recyclableWaste==null){
                recyclableWaste = new RecyclableWaste();
            }
            numberOfSyringes = numberOfSyringes+((String.valueOf(recyclableWaste.getNumberOfSyringes()))==null?0:recyclableWaste.getNumberOfSyringes());
            recyclableWaste.setNumberOfSyringes(numberOfSyringes);
            numberOfPlasticDisposables = numberOfPlasticDisposables+((String.valueOf(recyclableWaste.getNumberOfPlasticDisposables()))==null?0:recyclableWaste.getNumberOfPlasticDisposables());
            recyclableWaste.setNumberOfPlasticDisposables(numberOfPlasticDisposables);
            numberOfXRayFilms = numberOfXRayFilms+((String.valueOf(recyclableWaste.getNumberOfXRayFilms()))==null?0:recyclableWaste.getNumberOfXRayFilms());
            recyclableWaste.setNumberOfXRayFilms(numberOfXRayFilms);
            numberOfBPCuffsAndBulbs = numberOfBPCuffsAndBulbs+((String.valueOf(recyclableWaste.getNumberOfBPCuffAndBulbs()))==null?0:recyclableWaste.getNumberOfBPCuffAndBulbs());
            recyclableWaste.setNumberOfBPCuffAndBulbs(numberOfBPCuffsAndBulbs);
            recyclableWaste.setStatus("Completed");
            segregationResult.setDecomposableQuantity(decomposingQuantity);
            segregationResult.setRecyclableWaste(recyclableWaste);
            JOptionPane.showMessageDialog(null, "Recyclable Waste added Succesfully");
            request.setStatus("Completed");
         }
        
         syringesRecyclableJText.setText("");
         plasticDisposableRecyclableJText.setText("");
         xRayFilmsRecyclableJText.setText("");
         bpCuffsRecyclableJText.setText("");
         
         syringesTotalJText.setText("");
         plasticDisposablesTotalJText.setText("");
         xRayFilmsTotalJText.setText("");
         bpCuffsTotalJText.setText("");
         }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bpCuffsRecyclableJText;
    private javax.swing.JTextField bpCuffsTotalJText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField plasticDisposableRecyclableJText;
    private javax.swing.JTextField plasticDisposablesTotalJText;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField syringesRecyclableJText;
    private javax.swing.JTextField syringesTotalJText;
    private javax.swing.JTextField xRayFilmsRecyclableJText;
    private javax.swing.JTextField xRayFilmsTotalJText;
    // End of variables declaration//GEN-END:variables
}
