/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SegregatorWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonatingWaste;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.RecyclableWaste;
import Business.WorkQueue.SegregationTestWorkResult;
import Business.WorkQueue.WorkRequest;
import UserInterface.LabAssistant.LabAssistantWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author raunak
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
     private EcoSystem system;
     private UserAccount account;
     private Enterprise enterprise;
     //RecyclableWaste recyclableWaste = new RecyclableWaste();
    //private LabTestWorkRequest request;
   /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.enterprise= enterprise;
       
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel8.setVisible(false);
            
          jTextField1.setVisible(false);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          jTextField5.setVisible(false);  
          processToLabJText.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        segregationComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        processToLabJText = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        submitJButton.setBackground(new java.awt.Color(0, 153, 153));
        submitJButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        segregationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please choose from the below", "Decomposing Waste", "Donating Waste", "Recyclable Waste" }));
        segregationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segregationComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Please Select Waste Type : ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Segregator Work Area - Test Request");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("jLabel7");

        processToLabJText.setBackground(new java.awt.Color(0, 153, 153));
        processToLabJText.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        processToLabJText.setForeground(new java.awt.Color(255, 255, 255));
        processToLabJText.setText("Process To Lab");
        processToLabJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processToLabJTextActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("* Please dont leave the fields blank. Enter zero for empty fields.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addComponent(segregationComboBox, 0, 309, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(processToLabJText)
                                        .addGap(18, 18, 18)
                                        .addComponent(submitJButton))
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(segregationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processToLabJText)
                    .addComponent(submitJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents
    static boolean isNumberValid(String number)
    {
        String regex = "[\\\\s]*[0-9]*[0-9]+";
        return number.matches(regex);
    }
    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
       jTextField1.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel3.setForeground(Color.BLACK);
        
        jTextField2.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel4.setForeground(Color.BLACK);
        
        jTextField3.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel5.setForeground(Color.BLACK);
        
        jTextField4.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel6.setForeground(Color.BLACK);
        
        jTextField5.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel7.setForeground(Color.BLACK);
        
        if(segregationComboBox.getSelectedIndex()==1)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
        }
        else if(segregationComboBox.getSelectedIndex()==2){
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
            else if(isNumberValid(jTextField5.getText()) == false || jTextField5.getText() == null || jTextField5.getText().equals(""))
            {
                jTextField5.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel7.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel7.getText());
                return;
            }
            jLabel8.setVisible(true);
        }
        if(segregationComboBox.getSelectedIndex()==3)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
            jLabel8.setVisible(true);
        }
        
        ArrayList<WorkRequest> result = system.getWorkQueue().getWorkRequestList();
        SegregationTestWorkResult segregationResult=null;
       if(result==null || result.isEmpty()){
           segregationResult = new SegregationTestWorkResult();
          result.add(segregationResult);
       }
       
       for (int i=0; i<result.size();i++) {
          segregationResult = (SegregationTestWorkResult) result.get(i);
        if(segregationComboBox.getSelectedIndex()==1){
          double decomposableQuantity = Double.parseDouble(jTextField1.getText());
          decomposableQuantity = decomposableQuantity+segregationResult.getDecomposableQuantity();
          if(Integer.parseInt(jTextField1.getText())==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
        }
          segregationResult.setDecomposableQuantity(decomposableQuantity);
          segregationResult.setWasteType("Decomposing Waste");
          JOptionPane.showMessageDialog(null, "Decomposing Waste added Succesfully");
          jTextField1.setText("");
          return;
        }
        else if(segregationComboBox.getSelectedIndex()==2){
            int numberOfBeds = Integer.parseInt(jTextField1.getText());
            int numberOfWheelChairs = Integer.parseInt(jTextField2.getText());
            int numberOfBandages = Integer.parseInt(jTextField3.getText());
            int numberOfThermometers = Integer.parseInt(jTextField4.getText());
            int numberOfCrutches = Integer.parseInt(jTextField5.getText());
            
            if(numberOfThermometers==0&&numberOfBandages==0&&numberOfCrutches==0&&numberOfBeds==0&&numberOfWheelChairs==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
            }
            
            DonatingWaste donatingWaste = segregationResult.getDonatingWaste();
            if(donatingWaste==null){
                donatingWaste = new DonatingWaste();
            }
            numberOfBeds = numberOfBeds+((String.valueOf(donatingWaste.getNumberOfBeds()))==null?0:donatingWaste.getNumberOfBeds());
            donatingWaste.setNumberOfBeds(numberOfBeds);
            numberOfWheelChairs = numberOfWheelChairs+(String.valueOf(donatingWaste.getNumberOfWheelChairs())==null?0:donatingWaste.getNumberOfWheelChairs());
            donatingWaste.setNumberOfWheelChairs(numberOfWheelChairs);
            numberOfBandages = numberOfBandages+(String.valueOf(donatingWaste.getNumberOfBandages())==null?0:donatingWaste.getNumberOfBandages());
            donatingWaste.setNumberOfBandages(numberOfBandages);
            numberOfThermometers = numberOfThermometers+(String.valueOf(donatingWaste.getNumberOThermometers())==null?0:donatingWaste.getNumberOThermometers());
            donatingWaste.setNumberOThermometers(numberOfThermometers);
            numberOfCrutches =numberOfCrutches+(String.valueOf(donatingWaste.getNumberOfCrutches())==null?0:donatingWaste.getNumberOfCrutches());
            donatingWaste.setNumberOfCrutches(numberOfCrutches);
            segregationResult.setDonatingWaste(donatingWaste);
            JOptionPane.showMessageDialog(null, "Donating Waste added Succesfully");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
             return;
        }
       }
        for (Organization labOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             ArrayList<WorkRequest> labTestWorklist = labOrganization.getWorkQueue().getWorkRequestList();
               LabTestWorkRequest labTestWorkRequest = null;
                if(labTestWorklist==null || labTestWorklist.isEmpty()){
                  labTestWorkRequest = new LabTestWorkRequest();
                  labTestWorklist.add(labTestWorkRequest);
                }
          for(int i=0; i<labTestWorklist.size();i++){  
                labTestWorkRequest = (LabTestWorkRequest)labTestWorklist.get(i);
           if(segregationComboBox.getSelectedIndex()==3){
            int numberOfSyringes = Integer.parseInt(jTextField1.getText());
            int numberOfPlasticDisposables = Integer.parseInt(jTextField2.getText());
            int numberOfXRayFilms = Integer.parseInt(jTextField3.getText());
            int numberOfBPCuffsAndBulbs = Integer.parseInt(jTextField4.getText());
            
            if(numberOfSyringes==0&&numberOfPlasticDisposables==0&&numberOfBPCuffsAndBulbs==0&&numberOfXRayFilms==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
            }
            
            RecyclableWaste recyclableWaste = new RecyclableWaste();
            recyclableWaste.setNumberOfSyringes(numberOfSyringes);
            recyclableWaste.setNumberOfPlasticDisposables(numberOfPlasticDisposables);
            recyclableWaste.setNumberOfXRayFilms(numberOfXRayFilms);
            recyclableWaste.setNumberOfBPCuffAndBulbs(numberOfBPCuffsAndBulbs);
            
            
            numberOfSyringes = ((String.valueOf(recyclableWaste.getNumberOfSyringes()))==null?0:recyclableWaste.getNumberOfSyringes());
            recyclableWaste.setNumberOfSyringes(numberOfSyringes);
            numberOfPlasticDisposables = ((String.valueOf(recyclableWaste.getNumberOfPlasticDisposables()))==null?0:recyclableWaste.getNumberOfPlasticDisposables());
            recyclableWaste.setNumberOfPlasticDisposables(numberOfPlasticDisposables);
            numberOfXRayFilms = ((String.valueOf(recyclableWaste.getNumberOfXRayFilms()))==null?0:recyclableWaste.getNumberOfXRayFilms());
            recyclableWaste.setNumberOfXRayFilms(numberOfXRayFilms);
            numberOfBPCuffsAndBulbs = ((String.valueOf(recyclableWaste.getNumberOfBPCuffAndBulbs()))==null?0:recyclableWaste.getNumberOfBPCuffAndBulbs());
            recyclableWaste.setNumberOfBPCuffAndBulbs(numberOfBPCuffsAndBulbs);
            recyclableWaste.setStatus("Pending");
            
            labTestWorkRequest.setRecyclableWaste(recyclableWaste);
            labTestWorkRequest.setMessage("message");
            labTestWorkRequest.setSender(account);
            labTestWorkRequest.setStatus("Sent");

            JOptionPane.showMessageDialog(null, "Recyclable Waste added Succesfully");
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            submitJButton.setEnabled(false);
            processToLabJText.setEnabled(true);
             return;
         }
        }
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void segregationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segregationComboBoxActionPerformed
        if(segregationComboBox.getSelectedIndex()==1){
            jLabel3.setVisible(true);
            jLabel3.setText("Quantity(in lbs):");
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            
          jTextField1.setVisible(true);
          jTextField1.setText("");
          jTextField2.setVisible(false);
          jTextField2.setText("");
          jTextField3.setVisible(false);
          jTextField3.setText("");
          jTextField4.setVisible(false);
          jTextField4.setText("");
          jTextField5.setVisible(false); 
          jTextField5.setText("");
          
        }
        else if(segregationComboBox.getSelectedIndex()==2){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Beds");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Wheel chairs");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of Bandages");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of Thermometers");
            jLabel7.setVisible(true);
            jLabel7.setText("Number Of crutches");
            
            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(true);
            jTextField5.setText("");
            
        }
        else if(segregationComboBox.getSelectedIndex()==3){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Syringes");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Plastic Disposables");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of X-Ray Films");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of Blood Pressure Cuff and Flouroscent Bulb");
            jLabel7.setVisible(false);
           
            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(false);
            jTextField5.setText("");
            
        }
        else{
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            
          jTextField1.setVisible(false);
          jTextField1.setText("");
          jTextField2.setVisible(false);
          jTextField2.setText("");
          jTextField3.setVisible(false);
          jTextField3.setText("");
          jTextField4.setVisible(false);
          jTextField4.setText("");
          jTextField5.setVisible(false); 
          jTextField5.setText("");
          
        }
    }//GEN-LAST:event_segregationComboBoxActionPerformed

    private void processToLabJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processToLabJTextActionPerformed
         
//        LabAssistantWorkAreaJPanel labAssistantWorkAreaJPanel = new LabAssistantWorkAreaJPanel(userProcessContainer, system);
//        userProcessContainer.add("LabAssistantWorkAreaJPanel", labAssistantWorkAreaJPanel);
//        labAssistantWorkAreaJPanel.populateDetails(recyclableWaste);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
         //String message = messageJTextField.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage("message");
        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LabOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request raised to Lab");
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_processToLabJTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton processToLabJText;
    private javax.swing.JComboBox<String> segregationComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
